export enum ProfilesActionType {
  FETCH_PROFILE_REQUEST = "FETCH_PROFILE_REQUEST",
  FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS",
  FETCH_PROFILE_FAILURE = "FETCH_PROFILE_FAILURE",
  INVALIDATE_PROFILE = "INVALIDATE_PROFILE"
}
